<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy-简介" data-toc-modified-id="Numpy-简介-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy 简介</a></span></li><li><span><a href="#帮助" data-toc-modified-id="帮助-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>帮助</a></span></li><li><span><a href="#创建数组" data-toc-modified-id="创建数组-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>创建数组</a></span><ul class="toc-item"><li><span><a href="#初始占位符" data-toc-modified-id="初始占位符-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>初始占位符</a></span></li></ul></li><li><span><a href="#文件-I-/-O" data-toc-modified-id="文件-I-/-O-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>文件 I / O</a></span><ul class="toc-item"><li><span><a href="#在磁盘上保存-&amp;-加载" data-toc-modified-id="在磁盘上保存-&amp;-加载-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>在磁盘上保存 &amp; 加载</a></span></li><li><span><a href="#保存-&amp;-加载文本文件" data-toc-modified-id="保存-&amp;-加载文本文件-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>保存 &amp; 加载文本文件</a></span></li></ul></li><li><span><a href="#数据类型" data-toc-modified-id="数据类型-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>数据类型</a></span></li><li><span><a href="#检查数组" data-toc-modified-id="检查数组-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>检查数组</a></span></li><li><span><a href="#数学运算" data-toc-modified-id="数学运算-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>数学运算</a></span><ul class="toc-item"><li><span><a href="#算术运算" data-toc-modified-id="算术运算-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>算术运算</a></span></li><li><span><a href="#比较" data-toc-modified-id="比较-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>比较</a></span></li><li><span><a href="#聚合函数" data-toc-modified-id="聚合函数-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>聚合函数</a></span></li></ul></li><li><span><a href="#复制数组" data-toc-modified-id="复制数组-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>复制数组</a></span></li><li><span><a href="#排序数组" data-toc-modified-id="排序数组-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>排序数组</a></span></li><li><span><a href="#切片与索引" data-toc-modified-id="切片与索引-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>切片与索引</a></span><ul class="toc-item"><li><span><a href="#下标" data-toc-modified-id="下标-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>下标</a></span></li><li><span><a href="#切片" data-toc-modified-id="切片-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>切片</a></span></li><li><span><a href="#布尔索引" data-toc-modified-id="布尔索引-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>布尔索引</a></span></li></ul></li><li><span><a href="#数组操作" data-toc-modified-id="数组操作-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>数组操作</a></span><ul class="toc-item"><li><span><a href="#转置数组" data-toc-modified-id="转置数组-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>转置数组</a></span></li><li><span><a href="#改变形状" data-toc-modified-id="改变形状-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>改变形状</a></span></li><li><span><a href="#添加-/-删除元素" data-toc-modified-id="添加-/-删除元素-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>添加 / 删除元素</a></span></li><li><span><a href="#结合数组" data-toc-modified-id="结合数组-11.4"><span class="toc-item-num">11.4&nbsp;&nbsp;</span>结合数组</a></span></li><li><span><a href="#分割数组" data-toc-modified-id="分割数组-11.5"><span class="toc-item-num">11.5&nbsp;&nbsp;</span>分割数组</a></span></li></ul></li></ul></div>

## Numpy 简介

![Numpy](http://www.numpy.org/_static/numpy_logo.png)

Numpy 库是 Python 中科学计算的核心库。它提供了高性能的多维数组对象以及用于处理这些数组的工具。

使用以下约定导入 Numpy

In [1]:
import numpy as np

Numpy 数组

![Numpy Array](https://cdn-images-1.medium.com/max/2400/1*Ikn1J6siiiCSk4ivYUhdgw.png)

## 帮助

In [2]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## 创建数组

In [3]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)

### 初始占位符

In [4]:
# 创建一个零数组
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# 创建一个数组
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
# 创建均匀间隔值的数组（步长值）
d = np.arange(10,25,5)

In [7]:
# 创建均匀间隔值的数组（样本数）
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
# 创建常量数组
e = np.full((2,2),7)

In [9]:
# 创建2X2单位矩阵
f = np.eye(2)

In [10]:
# 创建具有随机值的数组
np.random.random((2,2))

array([[0.64234353, 0.07179718],
       [0.7937333 , 0.13764298]])

In [11]:
# 创建一个空数组
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 文件 I / O

### 在磁盘上保存 & 加载

In [12]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

### 保存 & 加载文本文件

In [ ]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")


## 数据类型

In [13]:
# 有符号的64位整数类型
np.int64

numpy.int64

In [14]:
# 标准双精度浮点复数
np.float32

numpy.float32

In [15]:
# 由128浮点数表示的布尔类型
np.complex

complex

In [16]:
# 存储TRUE和FALSE
np.bool

bool

In [17]:
# 值Python对象类型
np.object

object

In [18]:
# 固定长度的字符串类型
np.string_

numpy.bytes_

In [19]:
# 固定长度的unicode类型
np.unicode_

numpy.str_


## 检查数组

In [20]:
# 数组尺寸
a.shape

(3,)

In [21]:
# 数组长度
len(a)

3

In [22]:
# 数组维数
b.ndim

2

In [23]:
# 数组元素的数量
e.size

4

In [24]:
# 数组元素的数据类型
b.dtype

dtype('float64')

In [25]:
# 数据类型的名称
b.dtype.name

'float64'

In [26]:
# 将数组转换为其他类型
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## 数学运算

### 算术运算

In [27]:
# 减法
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
# 减法
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [29]:
# 加法
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [30]:
# 加法
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [31]:
# 乘法
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [32]:
# 除法
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [33]:
# 幂
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [34]:
# 平方根
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
# 正弦
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [36]:
# 余弦
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [37]:
# 自然对数
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [38]:
# 点积
e.dot(f)

array([[7., 7.],
       [7., 7.]])

### 比较

In [39]:
# 元素比较
a == b

array([[False,  True,  True],
       [False, False, False]])

In [40]:
# 元素比较
a < 2

array([ True, False, False])

In [41]:
# 数组比较
np.array_equal(a, b)

False

### 聚合函数

In [42]:
# 数组式和
a.sum()

6

In [43]:
# 数组最小值
a.min()

1

In [44]:
# 数组行的最大值
b.max(axis=0)

array([4., 5., 6.])

In [45]:
# 元素的累积总和
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [46]:
# 均值
a.mean()

2.0

In [47]:
# 中位数
np.median(b)

3.5

In [48]:
# 相关系数
np.corrcoef(a, b)

array([[1.        , 0.98198051, 1.        ],
       [0.98198051, 1.        , 0.98198051],
       [1.        , 0.98198051, 1.        ]])

In [49]:
# 标准差
np.std(b)

1.5920810978785667


## 复制数组

In [50]:
# 使用相同的数据创建数组视图
h = a.view()
h

array([1, 2, 3])

In [51]:
# 创建数组的副本
np.copy(a)

array([1, 2, 3])

In [52]:
# 创建数组的深层副本
h = a.copy()
h

array([1, 2, 3])


## 排序数组

In [53]:
# 对数组进行排序
a.sort()
a

array([1, 2, 3])

In [54]:
# 对数组轴的元素进行排序
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])


## 切片与索引

### 下标

In [55]:
a[2]

3

In [56]:
b[1,2]

6.0

### 切片

In [57]:
a[:2]

array([1, 2])

In [58]:
b[0:2,1]

array([2., 5.])

In [59]:
b[:1]

array([[1.5, 2. , 3. ]])

In [60]:
c[1, ...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [61]:
a[ : :-1]

array([3, 2, 1])

### 布尔索引

In [62]:
a[a<2]

array([1])

In [63]:
# 花式索引
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [64]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])


## 数组操作

### 转置数组

In [65]:
# 重新排列数组维度
i = np.transpose(b)

In [66]:
# 重新排列数组维度
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])


### 改变形状

In [67]:
# 展平数组
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [68]:
g.reshape(3, -2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

### 添加 / 删除元素

In [69]:
# 返回一个形状为新的数组（2,6）
h = np.array([1, 2, 3])
h.resize((2, 6))

In [70]:
# 将元素附加到数组
np.append(h, g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [71]:
# 在数组中插入元素
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [72]:
# 从数组中删除元素
np.delete(a,[1])

array([1, 3])

### 结合数组

In [73]:
# 连接数组
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [74]:
# 垂直堆叠数组（逐行）
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [75]:
# 垂直堆叠数组（逐行）
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [76]:
# 水平堆叠阵列（逐列）
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [77]:
# 创建堆叠的列式数组
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [78]:
# 创建堆叠的列式数组
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### 分割数组

In [79]:
# 在第3个索引处水平拆分数组
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [80]:
h
h.resize(2, 6)

In [81]:
# 在第 2 个索引处垂直拆分数组
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]